import { useState } from 'react'
import { SearchBox, buildSearchBox } from '@coveo/headless';
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { engine } from '../Engine'

const mySearchBox: SearchBox = buildSearchBox(engine);

export default function Home() {
  let [searchWord, setSearchWord] = useState('');

  engine.subscribe(()=>{
    console.log(mySearchBox.state.suggestions.map(el=>el.rawValue) );
  });

  const handleSubmit = (event) => {
    event.preventDefault();
    mySearchBox.updateText( searchWord );
  }

  const handleChange = (event) => {
    setSearchWord(event.target.value);
    event.preventDefault();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        Search:
        <form onSubmit={handleSubmit} >
          <input type="text" onChange={handleChange} value={searchWord} />
          <button type="submit">search</button>
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
